# Generated by Django 2.2.24 on 2021-11-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211112_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='we will add description soon', max_length=1500, null=True),
        ),
    ]
