# Generated by Django 2.2.24 on 2021-11-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211114_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingadress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='phone_number',
            field=models.CharField(default='+37400000000', max_length=12),
        ),
    ]
